### ISSUE TITLE
TT1 Blocks: Fix alignment on Cover Block

### ISSUE THREAD

**Issue by beafialho** [WordPress/theme-experiments#170]
While testing TT1 Blocks, I've encountered a bug on the Cover Block when choosing the Full Width option. Whether it's media or a color background, it doesn't stretch to the edge of the screen.

<img width="1536" alt="Captura de ecrã 2021-01-14, às 16 25 40" src="https://user-images.githubusercontent.com/65220155/104619057-5b758680-5685-11eb-8953-ac79e9745685.png">

**Comment by Jastos** [comment]
This will also happen on regular image blocks. 

`.wp-site-blocks *:not(.wp-block-post-content):not(.alignfull):not(.alignwide):not([class$="__inner-container"]) {
	max-width: var(--wp--custom--responsive--aligndefault-width);
}`

Does not allow the img tag to be full width since it is a child of the .alignfull on the figure element. A quick fix would be to add another :not, but this probably isn't the best solution.

`.wp-site-blocks *:not(.wp-block-post-content):not(.alignfull):not(.alignwide):not([class$="__inner-container"]):not(figure img) {
	max-width: var(--wp--custom--responsive--aligndefault-width);
}`
