### ISSUE TITLE
TT1 Blocks: Remove the Dark gray social link block style

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-experiments#176]
With the added [color options to the social links block](https://github.com/WordPress/gutenberg/pull/28084
), the block style is no longer needed, it is subpar to the new color settings.

And when the block style is selected in the block setting sidebar, the color options has no effect in the editor, only on the front,
this may cause confusion.

A question arises on how one can "migrate" existing block styles, for users who has already selected this style.
Especially if we consider making the same change to Twenty Twenty-One, once this option is added to WordPress core.

**Comment by kjellr** [comment]
> A question arises on how one can "migrate" existing block styles, for users who has already selected this style.
Especially if we consider making the same change to Twenty Twenty-One, once this option is added to WordPress core.

Good question — I was about to suggest that we remove the block style registration, but keep the styles in place for existing blocks... but then I realized that in order to remove these styles from existing blocks, folks would need to find the "CSS Classes" field and remove the classname. That seems cumbersome. 

Maybe it's better to just keep this block style in place, even though it can be reproduced by the new settings? It'll still work, so I don't think it does any harm to include it.

**Comment by carolinan** [comment]
_And when the block style is selected in the block setting sidebar, the color options has no effect in the editor, only on the front,
this may cause confusion._

**Comment by kjellr** [comment]
Oh ok I see what you mean. Yeah, this is a tough one. 🤔 Maybe removing this block style but keeping the CSS in place is the best overall move then.

**Comment by mtias** [comment]
That's how we have dealt with a few of the style variations removals before.
