### ISSUE TITLE
Twenty Twenty-One Blocks: Body line height is not correct. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/theme-experiments#76]
The Global `lineHeight` rule defined in `experimental-theme.json` isn't actually working yet:

https://github.com/WordPress/theme-experiments/blob/442adbfb4dd191c7cff7c33a22caef17c06eccf0/twentytwentyone-blocks/experimental-theme.json#L127

`lineHeight` works fine when it's applied to specific blocks, but the global value doesn't seem to be picked up. 🤔

@jorgefilipecosta or @nosolosw, do you know if this is a Gutenberg bug, or is it theme-related? We can specify the line height for the paragraph block (and other text blocks) if we need to, but it's much easier to set this at the global level first.

**Comment by jorgefilipecosta** [comment]
Thank you for letting us know about this issue @kjellr 👍  I added to my queue and should do some testing and debugging in the next few hours.

**Comment by nosolosw** [comment]
This is because the line height is not enabled for the global context. See (only fontSize is enabled) https://developer.wordpress.org/block-editor/developers/themes/theme-json/#typography-properties

It's an one-liner change, so I went ahead and prepared a PR https://github.com/WordPress/gutenberg/pull/26767

**Comment by kjellr** [comment]
Awesome, thank you! I can confirm that this solves the problem, so I'll close this issue.
